[package]
name = "r2t"
version = "0.4.0"
edition = "2024"
authors = ["Mostafa Alsari <mostafa.alsari@gmail.com>"]
description = "A fast CLI tool to convert a repository's structure and contents into a single text file, useful for providing context to LLMs."
license = "MIT"
readme = "README.md"
repository = "https://github.com/T00fy/r2t"
keywords = ["cli", "llm", "repository", "code", "context"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
directories = "6.0"
ignore = "0.4"
infer = "0.19"
ptree = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.33"
serde_json = "1.0.145"
globset = "0.4.18"

[dev-dependencies]
mockall = "0.13.1"
assert_cmd = "2.0"
predicates = "3.1"
tempfile = "3.10"
cargo-llvm-cov = "0.6.21"
